INSERT INTO TESTE_BB.CATEGORY VALUES (1, 'Alimentos');
INSERT INTO TESTE_BB.CATEGORY VALUES (2, 'Eletrodomésticos');
INSERT INTO TESTE_BB.CATEGORY VALUES (3, 'Móveis');
INSERT INTO TESTE_BB.CATEGORY VALUES (4, 'Brinquedos');
INSERT INTO TESTE_BB.CATEGORY VALUES (5, 'Medicamentos');

--------------------------------------------------------------

INSERT INTO TESTE_BB.PRODUCT VALUES (1, 'Arroz', 1);
INSERT INTO TESTE_BB.PRODUCT VALUES (2, 'Feijão', 1);
INSERT INTO TESTE_BB.PRODUCT VALUES (3, 'Aspirador de pó', 2);
INSERT INTO TESTE_BB.PRODUCT VALUES (4, 'Batedeira', 2);
INSERT INTO TESTE_BB.PRODUCT VALUES (5, 'Liquidificador', 2);
INSERT INTO TESTE_BB.PRODUCT VALUES (6, 'Sofá', 3);
INSERT INTO TESTE_BB.PRODUCT VALUES (7, 'Mesa', 3);
INSERT INTO TESTE_BB.PRODUCT VALUES (8, 'Estante', 3);