-- Populando a tabela CATEGORY
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.NEXTVAL, 'Alimentos');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.NEXTVAL, 'Eletrodomésticos');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.NEXTVAL, 'Móveis');

-- Populando a tabela PRODUCT
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'Arroz', 1);
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'Feijão', 1);
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'Aspirador de pó', 2);
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'Batedeira', 2);
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'Liquidificador', 2);
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'Sofá', 3);
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'Mesa', 3);
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'Estante', 3);
