CREATE SCHEMA IF NOT EXISTS TEST AUTHORIZATION SA;

CREATE SEQUENCE TEST.CATEGORY_SEQ MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE TEST.PRODUCT_SEQ MINVALUE 1 INCREMENT BY 1;


CREATE TABLE TEST.CATEGORY
(
  ID   INTEGER PRIMARY KEY,
  NAME VARCHAR(200)
);


CREATE TABLE TEST.PRODUCT
(
  ID          INTEGER PRIMARY KEY,
  NAME        VARCHAR(255),
  CATEGORY_ID INT,
  FOREIGN KEY (CATEGORY_ID) REFERENCES TEST.CATEGORY (ID)
);