CREATE SCHEMA IF NOT EXISTS TESTE_BB AUTHORIZATION SA;

DROP TABLE IF EXISTS TESTE_BB.CATEGORY;
DROP TABLE IF EXISTS TESTE_BB.PRODUCT;

CREATE TABLE TESTE_BB.CATEGORY (
	ID_CATEGORY IDENTITY PRIMARY KEY,
	DESCRIPTION VARCHAR(255),
);

CREATE TABLE TESTE_BB.PRODUCT (
	ID_PRODUCT IDENTITY PRIMARY KEY,
	DESCRIPTION VARCHAR(255),

	ID_CATEGORY BIGINT,

	FOREIGN KEY (ID_CATEGORY) REFERENCES TESTE_BB.CATEGORY(ID_CATEGORY)
);